# # -*- coding: utf-8 -*-
#
# # Form implementation generated from reading ui file 'get_vol_win.ui'
# #
# # Created by: PyQt5 UI code generator 5.15.0
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic5 is
# # run again.  Do not edit this file unless you know what you are doing.
#
#
# from PyQt5 import QtCore, QtGui, QtWidgets
#
#
# class Ui_Dialog1(object):
#     def setupUi(self, Dialog1):
#         Dialog1.setObjectName("Dialog1")
#         Dialog1.resize(212, 105)
#         self.pushButton = QtWidgets.QPushButton(Dialog1)
#         self.pushButton.setGeometry(QtCore.QRect(110, 70, 93, 28))
#         self.pushButton.setObjectName("pushButton")
#         self.lineEdit = QtWidgets.QLineEdit(Dialog1)
#         self.lineEdit.setGeometry(QtCore.QRect(10, 30, 151, 31))
#         self.lineEdit.setObjectName("lineEdit")
#         self.label = QtWidgets.QLabel(Dialog1)
#         self.label.setGeometry(QtCore.QRect(10, 10, 131, 16))
#         self.label.setObjectName("label")
#
#         self.retranslateUi(Dialog1)
#         QtCore.QMetaObject.connectSlotsByName(Dialog1)
#
#     def retranslateUi(self, Dialog):
#         _translate = QtCore.QCoreApplication.translate
#         Dialog.setWindowTitle(_translate("Dialog1", "Vol"))
#         self.pushButton.setText(_translate("Dialog1", "Ок"))
#         self.label.setText(_translate("Dialog1", "Введите объём судна"))